{{if not .Values.kubeconfig }}
---
apiVersion: {{ include "rbacversion" . }}
kind: ClusterRole
metadata:
  name: gardener.cloud:metrics-exporter
rules:
- apiGroups:
  - core.gardener.cloud
  resources:
  - shoots
  - projects
  - seeds
  - plants
  verbs:
  - get
  - watch
  - list
---
kind: ClusterRoleBinding
apiVersion: {{ include "rbacversion" . }}
metadata:
  name: gardener.cloud:metrics-exporter
subjects:
- kind: ServiceAccount
  name: gardener-metrics-exporter
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: gardener.cloud:metrics-exporter
  apiGroup: rbac.authorization.k8s.io
{{ end }}
